// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_xZ52--0w1hXYxvFs8J5yAYFxtyHy_A',
    appId: '1:255995108735:web:9ca45f180e718725b40e4a',
    messagingSenderId: '255995108735',
    projectId: 'agent36-4c6b6',
    authDomain: 'agent36-4c6b6.firebaseapp.com',
    storageBucket: 'agent36-4c6b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:255995108735:android:231b136c0ee26caab40e4a',
    messagingSenderId: '255995108735',
    projectId: 'agent36-4c6b6',
    storageBucket: 'agent36-4c6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:255995108735:ios:a80cc55f3e7b7a2db40e4a',
    messagingSenderId: '255995108735',
    projectId: 'agent36-4c6b6',
    storageBucket: 'agent36-4c6b6.firebasestorage.app',
    iosBundleId: 'com.example.agent36',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:255995108735:ios:a80cc55f3e7b7a2db40e4a',
    messagingSenderId: '255995108735',
    projectId: 'agent36-4c6b6',
    storageBucket: 'agent36-4c6b6.firebasestorage.app',
    iosBundleId: 'com.example.agent36',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:255995108735:web:992c5f57acd3a24fb40e4a',
    messagingSenderId: '255995108735',
    projectId: 'agent36-4c6b6',
    authDomain: 'agent36-4c6b6.firebaseapp.com',
    storageBucket: 'agent36-4c6b6.firebasestorage.app',
  );
}
